name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > androidApp/google-services.json
      - name: Build and upload
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
          
          echo "--------"
          ls androidApp/build/outputs/apk/release
          echo "--------"
          chmod +x ./upload-to-pgyer.sh  
          ./upload-to-pgyer.sh androidApp/build/outputs/apk/release/androidApp-release.apk
